In [2]:
import numpy as np

In [4]:
# seed is for research reproducibility


randoms=np.random.RandomState(seed=100)

X=randoms.uniform(low=0.0,high=1.0,size=(4,3))
print X


[[ 0.54340494  0.27836939  0.42451759]
 [ 0.84477613  0.00471886  0.12156912]
 [ 0.67074908  0.82585276  0.13670659]
 [ 0.57509333  0.89132195  0.20920212]]
